name: Package Sitecore Icons

on:
  push:
    tags: 
      - 'v*'

env:
  STATIC_VERSION: "1.0.1"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set Version
        run: |
          echo "VERSION=${env:STATIC_VERSION}.${env:GITHUB_RUN_NUMBER}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh
      - name: Info
        run: |
          Write-Host "Building Sitecore Icons"
          Write-Host "Version: ${env:VERSION}"
        shell: pwsh

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Add Sitecore Nuget Feed
        run: nuget.exe sources add -name Sitecore -source https://sitecore.myget.org/F/sc-packages/api/v3/index.json

      - name: Restore Packages
        run: nuget restore src/SitecoreIcons/SitecoreIcons.sln

      - name: Build Solution
        run: |
          msbuild.exe src/SitecoreIcons/SitecoreIcons.sln /p:Configuration=Debug

      - name: Publish Project
        run: |
          msbuild.exe src/SitecoreIcons/SitecoreIcons/SitecoreIcons.csproj /p:Configuration=Debug  /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Remove Roslyn Folder
        run: |
          if(Test-Path -Path "package/files/bin/roslyn") {
            Remove-Item -Path "package/files/bin/roslyn" -Force -Recurse
          }
        shell: pwsh

      - name: Download ImageMagick
        run: |
          curl https://imagemagick.org/archive/binaries/ImageMagick-7.1.0-portable-Q16-x64.zip -o tools\imagemagick.zip

      - name: Unzip ImageMagick using 7zip
        run: |
          7z x tools\imagemagick.zip -otools\imagemagick

      - name: Run Icons build
        run: |
          cd scripts
          .\main.ps1
          cd ..

      - name: Zip Icons
        run: |
          cd output
          7z a -tzip fa-black.zip fa-black
          7z a -tzip fa-blue.zip fa-blue
          7z a -tzip fa-green.zip fa-green
          7z a -tzip fa-red.zip fa-red
          7z a -tzip mui-black.zip mui-black
          7z a -tzip mui-blue.zip mui-blue
          7z a -tzip mui-green.zip mui-green
          7z a -tzip mui-red.zip mui-red
          Move-Item -Path "*.zip" -Destination "../package/files/sitecore/shell/Themes/Standard"
          cd ..
        shell: pwsh

      - name: Zip Sitecore package
        run: |
          dir
          cd package
          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files
          7z a -tzip SitecoreIcons-Full-${env:VERSION}.zip package.zip

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!mui-*"
          7z a -tzip SitecoreIcons-FontAwesome-${env:VERSION}.zip package.zip

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!fa-*"
          7z a -tzip SitecoreIcons-MUI-${env:VERSION}.zip package.zip

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!fa-*" "-xr!mui-green*" "-xr!mui-red*" "-xr!mui-blue*"
          7z a -tzip SitecoreIcons-MUI-Black-${env:VERSION}.zip package.zip 

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!fa-*" "-xr!mui-black*" "-xr!mui-red*" "-xr!mui-blue*"
          7z a -tzip SitecoreIcons-MUI-Green-${env:VERSION}.zip package.zip 

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!fa-*" "-xr!mui-green*" "-xr!mui-black*" "-xr!mui-blue*"
          7z a -tzip SitecoreIcons-MUI-Red-${env:VERSION}.zip package.zip 

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!fa-*" "-xr!mui-green*" "-xr!mui-red*" "-xr!mui-black*"
          7z a -tzip SitecoreIcons-MUI-Blue-${env:VERSION}.zip package.zip 

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!fa-*" "-xr!mui-green*" "-xr!mui-red*" "-xr!mui-blue*"
          7z a -tzip SitecoreIcons-MUI-Black-${env:VERSION}.zip package.zip

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!mui-*" "-xr!fa-green*" "-xr!fa-red*" "-xr!fa-blue*"
          7z a -tzip SitecoreIcons-FontAwesome-Black-${env:VERSION}.zip package.zip

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!mui-*" "-xr!fa-black*" "-xr!fa-red*" "-xr!fa-blue*"
          7z a -tzip SitecoreIcons-FontAwesome-Green-${env:VERSION}.zip package.zip

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!mui-*" "-xr!fa-green*" "-xr!fa-black*" "-xr!fa-blue*"
          7z a -tzip SitecoreIcons-FontAwesome-Red-${env:VERSION}.zip package.zip

          if(Test-Path -Path "package.zip") {
            Remove-Item -Path "package.zip"
          }
          7z a -tzip package.zip installer metadata files "-xr!mui-*" "-xr!fa-green*" "-xr!fa-red*" "-xr!fa-black*"
          7z a -tzip SitecoreIcons-FontAwesome-Blue-${env:VERSION}.zip package.zip
          cd ..
        shell: pwsh

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Full Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-Full-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-Full-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload Font Awesome Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-FontAwesome-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-FontAwesome-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload Font Awesome Black Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-FontAwesome-Black-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-FontAwesome-Black-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload Font Awesome Blue Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-FontAwesome-Blue-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-FontAwesome-Blue-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload Font Awesome Green Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-FontAwesome-Green-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-FontAwesome-Green-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload Font Awesome Red Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-FontAwesome-Red-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-FontAwesome-Red-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload MUI Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-MUI-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-MUI-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload MUI Black Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-MUI-Black-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-MUI-Black-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload MUI Blue Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-MUI-Blue-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-MUI-Blue-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload MUI Green Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-MUI-Green-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-MUI-Green-${{env.VERSION}}.zip
          asset_content_type: application/zip

      - name: Upload MUI Red Package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./package/SitecoreIcons-MUI-Red-${{env.VERSION}}.zip
          asset_name: SitecoreIcons-MUI-Red-${{env.VERSION}}.zip
          asset_content_type: application/zip