name: Package Sitecore Icons

on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
    
    - name: Add Sitecore Nuget Feed
      run: nuget.exe sources add -name Sitecore -source https://sitecore.myget.org/F/sc-packages/api/v3/index.json

    - name: Restore Packages
      run: nuget restore src/SitecoreIcons/SitecoreIcons.sln

    - name: Build Solution
      run: |
        msbuild.exe src/SitecoreIcons/SitecoreIcons.sln /p:Configuration=Debug

    - name: Publish Project
      run: |
        msbuild.exe src/SitecoreIcons/SitecoreIcons.csproj /p:Configuration=Debug /p:PublishProfile FolderProfile
        