name: Package Sitecore Icons

on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init --recursive
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE
    
    - name: Add Sitecore Nuget Feed
      run: nuget.exe sources add -name Sitecore -source https://sitecore.myget.org/F/sc-packages/api/v3/index.json

    - name: Restore Packages
      run: nuget restore src/SitecoreIcons/SitecoreIcons.sln

    - name: Build Solution
      run: |
        msbuild.exe src/SitecoreIcons/SitecoreIcons.sln /p:Configuration=Debug

    - name: Publish Project
      run: |
        msbuild.exe src/SitecoreIcons/SitecoreIcons/SitecoreIcons.csproj /p:Configuration=Debug /p:PublishProfile=FolderProfile

    - name: Remove Roslyn FolderProfile
      run: rmdir /s /q "package/files/bin/roslyn"

    - name: Download ImageMagick
      run: |
        curl https://imagemagick.org/archive/binaries/ImageMagick-7.1.0-portable-Q16-x64.zip -o tools\imagemagick.zip
        
    - name: Unzip ImageMagick using 7zip
      run: |
        7z x tools\imagemagick.zip -otools\imagemagick

    - name: Run Icons build
      run: |
        .\scripts\main.ps1

    - name: Zip Sitecore package
      run: |
        cd tools
        7z a -tzip package.zip files installer metadata
        cd ..

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: upload windows artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./package/package.zip
        asset_name: package.zip
        asset_content_type: application/zip